BookLibrary/BookLibrary/ViewModels/ManageLibrary/AddAuthorViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageLibrary
{
    public class AddAuthorViewModel
    {
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Required]
        [Display(Name = "Image")]
        public IFormFile Image { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }
    }
}

BookLibrary/BookLibrary/ViewModels/ManageLibrary/AddBookViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageLibrary
{
    public class AddBookViewModel
    {
        [Required]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Author")]
        public string AuthorId { get; set; }

        [Required]
        [Display(Name = "Realese year")]
        public int Year { get; set; }

        [Required]
        [Display(Name = "Image")]
        public IFormFile Image { get; set; }

        [Required]
        [Display(Name = "Book file")]
        public IFormFile FileBook { get; set; }

        [Required]
        [Display(Name = "Genre")]
        public string Genre { get; set; }

        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Initial rate")]
        public decimal Rate { get; set; }

        [Required]
        [Display(Name = "Rates amount")]
        public uint RatesAmount { get; set; }
    }
}

BookLibrary/BookLibrary/ViewModels/ManageLibrary/EditAuthorViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageLibrary
{
    public class EditAuthorViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Description { get; set; }
        public IFormFile Image { get; set; }
    }
}

BookLibrary/BookLibrary/ViewModels/ManageLibrary/EditBookViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageLibrary
{
    public class EditBookViewModel
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string AuthorId { get; set; }
        public int Year { get; set; }
        public IFormFile Image { get; set; }
        public IFormFile FileBook { get; set; }
        public string Genre { get; set; }
        public string Description { get; set; }
        public decimal Rate { get; set; }
        public uint RatesAmount { get; set; }
    }
}

BookLibrary/BookLibrary/Controllers/ManageLibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using Services.DTO;
using BookLibrary.ViewModels.ManageLibrary;
using System.IO;
using Microsoft.AspNetCore.Authorization;
using BookLibrary.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Services.Filters;

namespace BookLibrary.Controllers
{
    [Authorize(Roles = "library admin")]
    public class ManageLibraryController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IAuthorService _authorService;
        private readonly IRateService _rateService;
        private readonly ICommentService _commentService;
        public ManageLibraryController(IBookService bookService, IAuthorService authorService, IRateService rateService, ICommentService commentService)
        {
            _bookService = bookService;
            _authorService = authorService;
            _commentService = commentService;
            _rateService = rateService;
        }

        [HttpGet]
        public IActionResult Index() => View(_bookService.GetAll().ToList().OrderByDescending(b => b.Rate));

        [HttpGet]
        public IActionResult AddBook()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddBook(AddBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model == null)
                {
                    return RedirectToAction("Error");
                }
                BookDTO newBook = new BookDTO
                {
                    Title = model.Title.Trim(),
                    AuthorId = model.AuthorId,
                    Genre = model.Genre.Trim(),
                    Rate = model.Rate,
                    Description = model.Description,
                    Year = model.Year,
                    RatesAmount = model.RatesAmount
                };
                if (model.Image != null && model.FileBook != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(model.Image.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Image.Length);
                    }
                    newBook.Image = imageData;

                    byte[] fileData = null;
                    using (var binaryReader = new BinaryReader(model.FileBook.OpenReadStream()))
                    {
                        fileData = binaryReader.ReadBytes((int)model.FileBook.Length);
                    }
                    newBook.FileBook = fileData;
                }
                else
                {
                    return RedirectToAction("Error");
                }

                _bookService.Add(newBook);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditBook(string id)
        {
            //ViewBag.Authors = _authorService.GetAll().ToList();

            BookDTO getedBook = _bookService.Get(id);
            if (getedBook == null)
            {
                return RedirectToAction("Error");
            }
            EditBookViewModel model = new EditBookViewModel {
                Id = getedBook.Id,
                Title = getedBook.Title.Trim(),
                AuthorId = getedBook.AuthorId,
                Rate = getedBook.Rate,
                Year = getedBook.Year,
                Description = getedBook.Description,
                Genre = getedBook.Genre,
                RatesAmount = getedBook.RatesAmount
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult EditBook(EditBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model == null)
                {
                    return RedirectToAction("Error");
                }
                BookDTO editedBook = new BookDTO
                {
                    Id = model.Id,
                    Title = model.Title.Trim(),
                    AuthorId = model.AuthorId,
                    Genre = model.Genre,
                    Rate = model.Rate,
                    Description = model.Description,
                    Year = model.Year,
                    RatesAmount = model.RatesAmount
                };
                if (model.Image != null && model.FileBook != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(model.Image.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Image.Length);
                    }
                    editedBook.Image = imageData;

                    byte[] fileData = null;
                    using (var binaryReader = new BinaryReader(model.FileBook.OpenReadStream()))
                    {
                        fileData = binaryReader.ReadBytes((int)model.FileBook.Length);
                    }
                    editedBook.FileBook = fileData;
                }
                else
                {
                    return RedirectToAction("Error");
                }

                _bookService.Update(editedBook);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteBook(string id)
        {
            foreach (var c in _commentService.Get(new CommentFilter { CommentedEssenceId =  id}))
            {
                _commentService.Remove(c.Id);
            }
            foreach (var r in _rateService.Get(new RateFilterByBookId { BookId = id }))
            {
                _rateService.Remove(r.Id);
            }
            _bookService.Remove(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult AuthorsList() => View(_authorService.GetAll().ToList());

        [HttpGet]
        public IActionResult AddAuthor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddAuthor(AddAuthorViewModel model)
        {
            if (ModelState.IsValid)
            {

                if (model == null)
                {
                    return RedirectToAction("Error");
                }

                AuthorDTO newAuthor = new AuthorDTO
                {
                    Name = model.Name.Trim(),
                    Description = model.Description,
                    Surname = model.Surname.Trim()
                };
                if (model.Image != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(model.Image.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Image.Length);
                    }
                    newAuthor.Image = imageData;
                }
                else
                {
                    return RedirectToAction("Error");
                }
                _authorService.Add(newAuthor);
            }
            
            return RedirectToAction("AuthorsList");
        }

        [HttpGet]
        public IActionResult EditAuthor(string id)
        {
            AuthorDTO getedAuthor = _authorService.Get(id);
            if (getedAuthor == null)
            {
                return RedirectToAction("Error");
            }
            EditAuthorViewModel model = new EditAuthorViewModel
            {
                Name = getedAuthor.Name.Trim(),
                Surname = getedAuthor.Surname.Trim(),
                Description = getedAuthor.Description
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult EditAuthor(EditAuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model == null)
                {
                    throw new Exception();
                }

                AuthorDTO newAuthor = new AuthorDTO
                {
                    Id = model.Id,
                    Name = model.Name.Trim(),
                    Description = model.Description,
                    Surname = model.Surname.Trim()
                };
                if (model.Image != null)
                {
                    byte[] imageData = null;
                    using (var binaryReader = new BinaryReader(model.Image.OpenReadStream()))
                    {
                        imageData = binaryReader.ReadBytes((int)model.Image.Length);
                    }
                    newAuthor.Image = imageData;
                }
                else
                {
                    throw new Exception();
                }
                _authorService.Update(newAuthor);
            }
            return RedirectToAction("AuthorsList");
        }

        [HttpPost]
        public IActionResult DeleteAuthor(string id)
        {
            foreach (var c in _commentService.Get(new CommentFilter { CommentedEssenceId = id }))
            {
                _commentService.Remove(c.Id);
            }
            _authorService.Remove(id);
            return RedirectToAction("AuthorsList");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

BookLibrary/BookLibrary/Views/ManageLibrary/AddAuthor.cshtml
@model BookLibrary.ViewModels.ManageLibrary.AddAuthorViewModel
@{
        ViewData["Title"] = "Add author";
        Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h2 class="mt-5">Adding new author</h2>
    <div class="row">
        <div class="col-md-12">
            <form asp-action="AddAuthor" asp-controller="ManageLibrary" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input type="text" asp-for="Name" class="form-control form-control-lg" required />
                </div>
                <div class="form-group">
                    <label asp-for="Surname" class="control-label"></label>
                    <input type="text" asp-for="Surname" class="form-control form-control-lg" required />
                </div>
                <div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input type="file" asp-for="Image" class="form-control form-control-lg" required />
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <textarea asp-for="Description" class="form-control form-control-lg" rows="8"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Add author" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

BookLibrary/BookLibrary/Views/ManageLibrary/AddBook.cshtml
@using Services.Interfaces;
@model BookLibrary.ViewModels.ManageLibrary.AddBookViewModel
@{
    ViewData["Title"] = "Add new book";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject IAuthorService  authorService

<h2 class="mt-5">Adding new book</h2>
<div class="row">
    <div class="col-12">
        <form asp-action="AddBook" asp-controller="ManageLibrary" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input type="text" asp-for="Title" class="form-control" required />
            </div>
            <div class="form-row mt-5">
                <div class="col-1 d-flex align-items-center">
                    <label asp-for="AuthorId" class="control-label"></label>
                </div>
                <div class="col">
                    <select type="text" asp-for="AuthorId" class="form-control form-control-lg" required>
                        @foreach (var a in authorService.GetAll())
                        {
                            <option value="@a.Id">@a.Name @a.Surname</option>
                        }
                    </select>
                </div>
                <div class="col-2 d-flex justify-content-end">
                    <a class="btn btn-sm btn-success" asp-action="AddAuthor">Add new author</a>
                </div>
            </div>
            <div class="form-row my-5">
                <div class="col">
                    <label asp-for="Year" class="control-label"></label>
                    <input type="number" asp-for="Year" class="form-control form-control-lg" required />
                </div>
                <div class="col">
                    <label asp-for="Image" class="control-label"></label>
                    <input type="file" asp-for="Image" class="form-control form-control-lg" required />
                </div>
                <div class="col">
                    <label asp-for="FileBook" class="control-label"></label>
                    <input type="file" asp-for="FileBook" class="form-control form-control-lg" required />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input type="text" asp-for="Genre" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea type="text" asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-row my-5">
                <div class="col-lg-2">
                    @*<label asp-for="Rate" class="control-label"></label>*@
                    <input type="number" asp-for="Rate" value="0" hidden />

                    @*<select type="number" asp-for="Rate" class="form-control" required>
            @for (int i = 1; i <= 5; i++)
            {
                <option value="@i">@i</option>
            }
        </select>*@
                </div>
                <div class="col-lg-2">
                    @*<label asp-for="RatesAmount" class="control-label"></label>*@
                    <input type="number" asp-for="RatesAmount" value="0" hidden />
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

BookLibrary/BookLibrary/Views/ManageLibrary/AuthorsList.cshtml
@model IEnumerable<Services.DTO.AuthorDTO>
@{
    ViewData["Title"] = "Authors list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-5">Authors list</h2>
<a class="btn btn-success" asp-action="AddAuthor">Add author</a>
<a class="btn btn-default" asp-action="Index">Books list</a>
<table class="table mt-5">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var author in Model)
        {
            int i = 0;
            i += 1;
            <tr>
                <th scope="row">@i</th>
                <td>@author.Name</td>
                <td>@author.Surname</td>
                <td>
                    <form asp-action="DeleteAuthor" asp-route-id="@author.Id" method="post">
                        <a class="btn btn-sm btn-primary" asp-action="EditAuthor" asp-route-id="@author.Id">Edit</a>
                        <button type="submit" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }

</table>

BookLibrary/BookLibrary/Views/ManageLibrary/EditAuthor.cshtml
@model BookLibrary.ViewModels.ManageLibrary.EditAuthorViewModel
@{
    ViewData["Title"] = "Edit author";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="mt-5">Author editing</h2>
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditAuthor" asp-controller="ManageLibrary" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
            </div>
            <div class="form-group">
                <label class="control-label">Name</label>
                <input type="text" asp-for="Name" class="form-control form-control-lg" required />
            </div>
            <div class="form-group">
                <label class="control-label">Surname</label>
                <input type="text" asp-for="Surname" class="form-control form-control-lg" required />
            </div>
            <div class="form-group">
                <label class="control-label">Image</label>
                <input type="file" asp-for="Image" class="form-control form-control-lg" required />
            </div>
            <div class="form-group">
                <label class="control-label">Description</label>
                <textarea type="text" asp-for="Description" class="form-control form-control-lg"></textarea>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>

    </div>
</div>

BookLibrary/BookLibrary/Views/ManageLibrary/EditBook.cshtml
@using Services.Interfaces;
@model BookLibrary.ViewModels.ManageLibrary.EditBookViewModel
@{
    ViewData["Title"] = "Edit book";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject IAuthorService authorService
<h2 class="mt-5">Book editing</h2>
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditBook" asp-controller="ManageLibrary" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
            </div>
            <div class="form-group">
                <label class="control-label">Title</label>
                <input type="text" asp-for="Title" class="form-control" required />
            </div>
            <div class="form-row mt-5">
                <div class="col-1 d-flex align-items-center">
                    <label class="control-label">Author</label>
                </div>
                <div class="col">
                    <select type="text" asp-for="AuthorId" class="form-control form-control-lg" required>
                        @foreach (var a in authorService.GetAll())
                        {
                            <option value="@a.Id">@a.Name @a.Surname</option>
                        }
                    </select>
                </div>
                <div class="col-2 d-flex justify-content-end">
                    <a class="btn btn-sm btn-success" asp-action="AddAuthor">Add new author</a>
                </div>
            </div>
            <div class="form-row my-5">
                <div class="col">
                    <label class="control-label">Year</label>
                    <input type="number" asp-for="Year" class="form-control form-control-lg" required />
                </div>
                <div class="col">
                    <label class="control-label">Image</label>
                    <input type="file" asp-for="Image" class="form-control form-control-lg" required />
                </div>
                <div class="col">
                    <label class="control-label">Book file</label>
                    <input type="file" asp-for="FileBook" class="form-control form-control-lg" required />
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Genre</label>
                <input type="text" asp-for="Genre" class="form-control" required />
            </div>
            <div class="form-group">
                <label class="control-label">Description</label>
                <textarea type="text" asp-for="Description" class="form-control"></textarea>
            </div>
            <div class="form-group">
                @*<label class="control-label">Rate</label>*@
                <input type="number" asp-for="Rate" hidden />
                @*<select type="number" asp-for="Rate" class="form-control" required>
                    @for (int i = 1; i <= 5; i++)
                    {
                        <option value="@i">@i</option>
                    }
                </select>*@
            </div>
            <div class="form-group">
                @*<label class="control-label">Rates Amount</label>*@
                <input type="number" asp-for="RatesAmount" hidden />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

BookLibrary/BookLibrary/Views/ManageLibrary/Index.cshtml
@model IEnumerable<Services.DTO.BookDTO>
@{
    ViewData["Title"] = "Books list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-5">Books List</h2>
<a class="btn btn-success" asp-action="AddBook">Add book</a>
<a class="btn btn-default" asp-action="AuthorsList">Authors list</a>
<table class="table mt-5">
    <thead class="thead-light">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Year</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            int i = 0;
            i += 1;
            <tr>
                <th scope="row">@i</th>
                <td>@book.Title</td>
                <td>@book.Year</td>
                <td>
                    <form asp-action="DeleteBook" asp-route-id="@book.Id" method="post" class="d-flex justify-content-end">
                        <a class="btn btn-sm btn-primary" asp-action="EditBook" asp-route-id="@book.Id">Edit</a>
                        <button type="submit" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </td>
            </tr>
        }

</table>