BookLibrary/BookLibrary/ViewModels/ManageComments/CommentedEssenceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageComments
{
    public class CommentedEssenceViewModel
    {
        public string EssenceId { get; set; }
        public bool isBook { get; set; }
    }
}

BookLibrary/BookLibrary/Controllers/ManageCommentsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BookLibrary.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.DTO;
using Services.Interfaces;

namespace BookLibrary.Controllers
{
    public class ManageCommentsController : Controller
    {
        
        private readonly ICommentService _commentService;

        public ManageCommentsController(ICommentService commentService)
        {
            _commentService = commentService;
        }
        
        [HttpPost]
        public IActionResult EditComment(string id, string ownerId, string essenceId, string isBook, string time, string text)
        {
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(ownerId) || string.IsNullOrEmpty(essenceId) || string.IsNullOrEmpty(isBook) || string.IsNullOrEmpty(text) || string.IsNullOrEmpty(time))
            {
                RedirectToAction("Error");
            }

            if (!bool.TryParse(isBook, out bool isBookToParse))
            {
                RedirectToAction("Error");
            }
            if (!DateTime.TryParse(time, out DateTime dateTime))
            {
                RedirectToAction("Error");
            }

            CommentDTO updatedComment = new CommentDTO
            {
                Id = id,
                OwnerId = ownerId,
                CommentedEssenceId = essenceId,
                Text = text,
                Time = dateTime
            };
            _commentService.Update(updatedComment);
            if (isBookToParse)
            {
                return RedirectToAction("GetBookInfo", "Home", new { id = essenceId });
            }
            else
            {
                return RedirectToAction("GetAuthorInfo", "Home", new { id = essenceId });
            }
        }

        [HttpPost]
        public IActionResult DeleteComment(string comentId, string isBook, string essenceId)
        {
            if (string.IsNullOrEmpty(comentId) || string.IsNullOrEmpty(isBook) || string.IsNullOrEmpty(essenceId))
            {
                RedirectToAction("Error");
            }
            if (!bool.TryParse(isBook, out bool isBookToParse))
            {
                return RedirectToAction("Error");
            }


            if (_commentService.Get(comentId) == null)
            {
                RedirectToAction("Error");
            }
            _commentService.Remove(comentId);
            if (isBookToParse)
            {
                return RedirectToAction("GetBookInfo", "Home", new { id = essenceId });
            }
            else
            {
                return RedirectToAction("GetAuthorInfo", "Home", new { id = essenceId });
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddComment(string ownerId, string essenceId, string isBook, string text)
        {
            
            if (string.IsNullOrEmpty(ownerId) || string.IsNullOrEmpty(essenceId) || string.IsNullOrEmpty(isBook) || string.IsNullOrEmpty(text))
            {
                RedirectToAction("Error");
            }
            if (!bool.TryParse(isBook, out bool isBookToParse))
            {
                return RedirectToAction("Error");
            }

            CommentDTO newComment = new CommentDTO
            {
                OwnerId = ownerId,
                CommentedEssenceId = essenceId,
                Text = text,
                Time = DateTime.Now
            };
            _commentService.Add(newComment);
            if (isBookToParse)
            {
                return RedirectToAction("GetBookInfo", "Home", new { id = essenceId });
            }
            else
            {
                return RedirectToAction("GetAuthorInfo", "Home", new { id = essenceId });
            }
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookLibrary/BookLibrary/Views/ManageComments/_CommentPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using Services.Interfaces;
@using Services.Filters;

@inject ICommentService commentServive
@inject UserManager<IdentityUser> UserManager
@inject SignInManager<IdentityUser> SignInManager


@model BookLibrary.ViewModels.ManageComments.CommentedEssenceViewModel

<h3 class="mt-5">Add your comment</h3>
@if (SignInManager.IsSignedIn(User))
{
    <form asp-action="AddComment" asp-controller="ManageComments" method="post">
        <div class="form-group">
            <input type="hidden" name="ownerId" value="@((await UserManager.GetUserAsync(User)).Id)" />
        </div>
        <div class="form-group">
            <input type="hidden" name="essenceId" value="@Model.EssenceId" />
        </div>
        <div class="form-group">
            <input type="hidden" name="isBook" value="@Model.isBook.ToString()" />
        </div>
        <div class="form-group">
            <textarea class="form-control" name="text" required rows="5"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="Comment" class="btn btn-success" />
        </div>
    </form>
}
else
{
    <form asp-action="AddComment" asp-controller="ManageComments" method="post">
        <div class="form-group">
            <textarea class="form-control" disabled rows="5"></textarea>
        </div>
        <div class="form-group">
            <input type="submit" value="Comment" class="btn btn-success" />
        </div>
    </form>
}

<hr style="border-width: 3px; border-color: grey;" />
<h3>All Comments</h3>
@foreach (var c in commentServive.Get(new CommentFilter { CommentedEssenceId = Model.EssenceId }).OrderByDescending(c => c.Time))
{
    <div class="row">
        @if ((SignInManager.IsSignedIn(User)) && ((await UserManager.GetUserAsync(User)).Id == c.OwnerId))
        {
            <div class="col-lg-12">

                <p style="color:dodgerblue">
                    <b><ins>You</ins> @c.Time</b>
                </p>

                <div class="col-lg-11">
                    <form asp-action="EditComment" asp-controller="ManageComments" method="post">
                        <div class="form-group">
                            <input type="hidden" name="id" value="@c.Id" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="ownerId" value="@((await UserManager.GetUserAsync(User)).Id)" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="essenceId" value="@Model.EssenceId" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="isBook" value="@Model.isBook.ToString()" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="time" value="@c.Time.ToString()" />
                        </div>
                        <div class="form-group">
                            <textarea class="form-control" name="text">@c.Text</textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Edit" class="btn btn-sm btn-success" />
                        </div>
                    </form>
                </div>
                <div class="col-lg-1">
                    <form asp-action="DeleteComment" asp-controller="ManageComments" method="post">
                        @*asp-route-id="@c.Id"*@
                        <div class="form-group">
                            <input type="hidden" name="comentId" value="@c.Id" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="essenceId" value="@Model.EssenceId" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="isBook" value="@Model.isBook.ToString()" />
                        </div>
                        <button type="submit" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div>
        }
        else if ((SignInManager.IsSignedIn(User)) &&
        (await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "user admin")) &&
        !(await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "library admin")))
        {

            @if ((await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "user admin")) &&
  (await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "library admin")))
            {
                <div class="col-lg-11">
                    <p><ins style="color:black">@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins>   <em style="color:darkblue; font-size: small;">@c.Time</em></p>
                    <div class="form-group">
                        <p class="h4 text-secondary border px-3 py-2 rounded">@c.Text</p>
                    </div>
                </div>
            }
            else if ((await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "user admin")))
            {
                <div class="col-lg-11">
                    <p style="color:firebrick"><ins style="color:black">@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> User admin @c.Time</p>
                    <div class="form-group">
                        <p class="h4 text-secondary border px-3 py-2 rounded">@c.Text</p>
                    </div>
                </div>
            }
            else
            {
                <div class="col-lg-12">
                    @if ((await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "library admin")))
                    {
                        <p style="color: seagreen"><ins style="color:black">@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> Library admin @c.Time</p>
                    }
                    else
                    {
                        <p style="color:dimgrey"><ins>@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> @c.Time</p>
                    }
                    <div class="col-lg-11">
                        <div class="form-group">
                            <p class="h4 text-secondary border px-3 py-2 rounded">@c.Text</p>
                        </div>
                    </div>
                    <div class="col-lg-1">
                        <form asp-action="DeleteComment" asp-controller="ManageComments" method="post">
                            <div class="form-group">
                                <input type="hidden" name="comentId" value="@c.Id" />
                            </div>
                            <div class="form-group">
                                <input type="hidden" name="essenceId" value="@Model.EssenceId" />
                            </div>
                            <div class="form-group">
                                <input type="hidden" name="isBook" value="@Model.isBook.ToString()" />
                            </div>
                            <button type="submit" class="btn btn-sm btn-danger">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            }
        }
        else if ((SignInManager.IsSignedIn(User)) &&
        (await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "user admin")) &&
        (await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "library admin")))
        {

            <div class="col-lg-12">
                @if ((await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "user admin")))
                {
                    <p style="color: firebrick"><ins style="color:black">@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> User admin @c.Time</p>
                }
                else if ((await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "library admin")))
                {
                    <p style="color: seagreen"><ins style="color:black">@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> Library admin @c.Time</p>
                }
                else
                {
                    <p style="color:dimgrey"><ins>@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> @c.Time</p>
                }
                <div class="col-lg-11">
                    <div class="form-group">
                        <p class="h4 text-secondary border px-3 py-2 rounded">@c.Text</p>
                    </div>
                </div>
                <div class="col-lg-1">
                    <form asp-action="DeleteComment" asp-controller="ManageComments" method="post">
                        <div class="form-group">
                            <input type="hidden" name="comentId" value="@c.Id" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="essenceId" value="@Model.EssenceId" />
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="isBook" value="@Model.isBook.ToString()" />
                        </div>
                        <button type="submit" class="btn btn-sm btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div>

        }
        else
        {
            @if ((await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "user admin")) ||
   (await UserManager.IsInRoleAsync((UserManager.Users.First(u => u.Id == c.OwnerId)), "library admin")))
            {
                <div class="col-lg-11">
                    <p style="color: red"><ins style="color:black">@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> Admin @c.Time</p>
                </div>
            }
            else
            {
                <div class="col-lg-11">
                    <p style="color:dimgrey"><ins>@((UserManager.Users.First(u => u.Id == c.OwnerId)).UserName)</ins> @c.Time</p>
                </div>
            }
            <div class="col-lg-11">
                <div class="form-group">
                    <p class="h4 text-secondary border px-3 py-2 rounded">@c.Text</p>
                </div>
            </div>
        }

    </div>
    <hr style="border-width: 2px; border-color: grey;" />

}