BookLibrary/BookLibrary/ViewModels/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels
{
    public class EditUserViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
    }
}

BookLibrary/BookLibrary/ViewModels/ManageUsers/ChangeRoleViewModel.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageUsers
{
    public class ChangeRoleViewModel
    {
        public string UserId { get; set; }
        public string UserEmail { get; set; }
        public List<IdentityRole> AllRoles { get; set; }
        public IList<string> UserRoles { get; set; }
        public ChangeRoleViewModel()
        {
            AllRoles = new List<IdentityRole>();
            UserRoles = new List<string>();
        }
    }
}

BookLibrary/BookLibrary/ViewModels/ManageUsers/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookLibrary.ViewModels.ManageUsers
{
    public class EditUserViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string LoginName { get; set; }
    }
}

BookLibrary/BookLibrary/Controllers/ManageUsersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using BookLibrary.Models;
using BookLibrary.ViewModels.ManageUsers;
using DataAccess.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Services.Interfaces;
using Services.Filters;

namespace BookLibrary.Controllers
{
    [Authorize(Roles = "user admin")]
    public class ManageUsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ICommentService _commentService;
        public ManageUsersController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager, ICommentService commentService)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _commentService = commentService;
        }

        [HttpGet]
        public IActionResult Index() => View();

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return RedirectToAction("Error");
            }
            EditUserViewModel model = new EditUserViewModel { Id = user.Id, Email = user.Email, LoginName = user.UserName };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    user.UserName = model.LoginName;

                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    return RedirectToAction("Error");
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id)
        {
            IdentityUser user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    return RedirectToAction("Error");
                }
            }
            foreach (var c in _commentService.Get(new CommentFilterByOwnerId { OwnerId = id }))
            {
                _commentService.Remove(c.Id);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> EditUserRoles(string userId)
        {
            // get user
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // gets user`s roles list
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return RedirectToAction("Error");
        }
        [HttpPost]
        public async Task<IActionResult> EditUserRoles(string userId, List<string> roles)
        {
            // gets user
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // gets user`s roles list
                var userRoles = await _userManager.GetRolesAsync(user);
                // gets all roles
                var allRoles = _roleManager.Roles.ToList();
                // gets roles list, that was added 
                var addedRoles = roles.Except(userRoles);
                // gets roles that was deleted
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);

                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index");
            }

            return RedirectToAction("Error");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookLibrary/BookLibrary/Views/ManageUsers/EditUser.cshtml
@model BookLibrary.ViewModels.ManageUsers.EditUserViewModel
@{
    ViewData["Title"] = "Edit user";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row ">
    <div class="col-md-12">
        <form asp-action="EditUser" asp-controller="ManageUsers">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" asp-for="Id" />
            </div>
            <div class="form-group">
                <label class="control-label">Email</label>
                <input type="text" asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Login name</label>
                <input type="text" asp-for="LoginName" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

BookLibrary/BookLibrary/Views/ManageUsers/EditUserRoles.cshtml
@using Microsoft.AspNetCore.Identity
@model BookLibrary.ViewModels.ManageUsers.ChangeRoleViewModel
@{
    ViewData["Title"] = "Changing user roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="mt-5">Changing roles for user @Model.UserEmail</h2>

<form asp-action="EditUserRoles" method="post">
    <input type="hidden" name="userId" value="@Model.UserId" />
    <div class="form-group">
        @foreach (IdentityRole role in Model.AllRoles)
        {
        <div class="d-flex">
            <div class="input-group-prepend">
                <div class="input-group-text bg-white border-0">
                    <input type="radio" name="roles" value="@role.Name"
                           @(Model.UserRoles.Contains(role.Name) ? "checked=\"checked\"" : "")>
                        <span class="checkmark"></span>
                    </div>
                </div>

            <label class="pl-3 h4 m-0">@role.Name</label>
            </div>
            }
    </div>
    <button type="submit" class="btn btn-success">Save</button>
</form>

BookLibrary/BookLibrary/Views/ManageUsers/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@{
    ViewData["Title"] = "Users list";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject UserManager<IdentityUser> UserManager
@inject SignInManager<IdentityUser> SignInManager
    <h2 class="mt-5">Users List</h2>

    <table class="table mt-5">
        <thead class="thead-light">
            <tr>
                <th scope="col">#</th>
                <th scope="col">Email</th>
                <th scope="col">Login name</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in UserManager.Users)
            {
                int i = 0;
                i += 1;
                <tr>
                    <th scope="row">@i</th>
                    <td>@user.Email</td>
                    <td>@user.UserName</td>
                    <td class="d-flex justify-content-end">
                        @if ((await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "library admin")) || (await UserManager.IsInRoleAsync((await UserManager.GetUserAsync(User)), "user admin")))
                        {
                            if (!(await UserManager.IsInRoleAsync(user, "user admin")) || !(await UserManager.IsInRoleAsync(user, "library admin")))
                            {
                                <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                                    <a class="btn btn-sm btn-primary" asp-action="EditUser" asp-route-id="@user.Id">Edit</a>
                                    <a class="btn btn-sm btn-primary" asp-action="EditUserRoles" asp-route-userid="@user.Id">Access rights</a>
                                    <button type="submit" class="btn btn-sm btn-danger">
                                        Delete
                                    </button>
                                </form>
                            }
                        }
                        else if (!(await UserManager.IsInRoleAsync(user, "user admin")))
                        {
                            <form asp-action="DeleteUser" asp-route-id="@user.Id" method="post">
                                <a class="btn btn-sm btn-primary" asp-action="EditUser" asp-route-id="@user.Id">Edit</a>
                                <a class="btn btn-sm btn-primary" asp-action="EditUserRoles" asp-route-userid="@user.Id">Access rights</a>
                                <button type="submit" class="btn btn-sm btn-danger">
                                    Delete
                                </button>
                            </form>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>